/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planes/grass-tile/grass-tile-1.gltf --transform 
Files: public/models/planes/grass-tile/grass-tile-1.gltf [11.2KB] > D:\work\websites\greenteam\grass-tile-1-transformed.glb [5.7KB] (49%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/grass-tile-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Dirt} />
      <mesh geometry={nodes.Grass.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Grass_1.geometry} material={materials['Grass-tall']} position={[-0.092, 0.794, -0.487]} rotation={[Math.PI, 0, Math.PI]} scale={0.342} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Rock.001']} position={[-0.497, 1.006, 0.31]} scale={[1, 0.558, 1]} />
    </group>
  )
}

useGLTF.preload('/grass-tile-1-transformed.glb')
