//@ts-nocheck
"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planes/dirt-tile/dirt-road-1.gltf --transform 
Files: public/models/planes/dirt-tile/dirt-road-1.gltf [8.48KB] > D:\work\websites\greenteam\dirt-road-1-transformed.glb [4.93KB] (42%)
*/

import React, { useEffect, useRef, useState } from "react"
import { useGLTF } from "@react-three/drei"

export default function DirtRoad({ position, rotation, kind }) {
    const { nodes, materials } = useGLTF(
        "/models/transformed/dirt-road-1-transformed.glb",
    )

    const [hovered, setHovered] = useState(false)
    const dirtRef = useRef<THREE.Mesh>(null!)
    useEffect(() => {
        dirtRef.current.material = hovered ? materials.Rock : materials.Dirt
    }, [hovered])
    if (kind === 0) {
        return (
            <group position={position} rotation={rotation} dispose={null}>
                <mesh
                    ref={dirtRef}
                    geometry={nodes.Cube001.geometry}
                    material={materials.Dirt}
                    onPointerEnter={() => setHovered(true)}
                    onPointerLeave={() => setHovered(false)}
                />
                <mesh
                    geometry={nodes.Sphere001.geometry}
                    material={materials.Rock}
                    position={[0.719, 0.996, -0.152]}
                    scale={[0.729, 0.28, 0.729]}
                />
            </group>
        )
    } else {
        return (
            <group position={position} rotation={rotation} dispose={null}>
                <mesh
                    ref={dirtRef}
                    geometry={nodes.Cube001.geometry}
                    material={materials.Dirt}
                    onPointerEnter={() => setHovered(true)}
                    onPointerLeave={() => setHovered(false)}
                />
            </group>
        )
    }
}

useGLTF.preload("/models/transformed/dirt-road-1-transformed.glb")
useGLTF.preload("/models/transformed/dirt-road-2-transformed.glb")
