"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/trees/planted-tree-1.gltf --transform -t -j -M 
Files: public/models/trees/planted-tree-1.gltf [5.56KB] > D:\work\websites\greenteam\planted-tree-1-transformed.glb [4.18KB] (25%)
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
    nodes: {
        Leaves1: THREE.Mesh
        Leaves2: THREE.Mesh
        Leaves3: THREE.Mesh
        Base: THREE.Mesh
    }
    materials: {
        LeafMaterial: THREE.MeshStandardMaterial
        BaseMaterial: THREE.MeshStandardMaterial
    }
    animations: any[]
}

type ContextType = Record<
    string,
    React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>

export default function PlantedTree(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(
        "/models/transformed/planted-tree-1-transformed.glb",
    ) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Leaves1.geometry}
                material={materials.LeafMaterial}
                position={[0.623, 1.912, -0.421]}
                rotation={[-0.1, -0.237, -1.842]}
                scale={-0.09}
            />
            <mesh
                geometry={nodes.Leaves2.geometry}
                material={materials.LeafMaterial}
                position={[-0.121, 1.158, -0.187]}
                rotation={[0.921, 0.508, 0.768]}
                scale={-0.058}
            />
            <mesh
                geometry={nodes.Leaves3.geometry}
                material={materials.LeafMaterial}
                position={[-0.077, 1.855, 0.024]}
                rotation={[0.921, 0.508, 0.768]}
                scale={-0.082}
            />
            <mesh
                geometry={nodes.Base.geometry}
                material={materials.BaseMaterial}
            />
        </group>
    )
}

useGLTF.preload("/models/transformed/planted-tree-1-transformed.glb")
